### ISSUE TITLE
Python 3.8 should be fine, does it

### ISSUE THREAD

**Issue by shawn0915** [tidb-samples/tidb-python-mysqlclient-quickstart#2]
readme 中描述，需要 [Python 3.10 or higher](https://www.python.org/downloads/)
实际上，只需要保证 python 3.8 及以上版本即可，对吧？
(from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.8)

另外，建议升级 mysqlclient==2.2.0 到 2.2.1

**Comment by wd0517** [comment]
是的，mysqlclient 只要求 python3.8，我改一下
